# Generated by Django 4.2

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveSmallIntegerField(unique=True)),
                ('board', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='active_board_ids',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='boards',
        ),
        migrations.AddField(
            model_name='gameround',
            name='active_card_numbers',
            field=models.JSONField(default=list),
        ),
    ]