# Generated by Django 5.0.6

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_permanent_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='commission_percentage',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(35)]),
        ),
    ]